// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Arthes.DATA.Models
{
    public partial class Fabricante
    {
        public Fabricante()
        {
            Linha = new HashSet<Linha>();
        }

        [Key]
        public int Id { get; set; }

        public string Nome { get; set; }

        [InverseProperty("Fabricante")]
        public virtual ICollection<Linha> Linha { get; set; }
    }
}